sudo: required
dist: trusty
language: node_js
node_js:
- '7'
services:
- postgresql
addons:
  postgresql: '9.4'
  hosts:
    - api.test
cache:
  directories:
    - 'node_modules'
    - '/tmp/bundler'
before_install:
- npm install -g codeclimate-test-reporter
- git clone https://${TOKEN}:x-oauth-basic@github.com/meedan/configurator ./configurator
- sudo rm /etc/apt/sources.list.d/mongodb*
- sudo apt-get -qq update
- sudo apt-get install wget python-setuptools lsof unzip imagemagick ruby ruby-dev libnss3 libnss3-dev xvfb libnss3-1d libexif-dev curl build-essential libssl-dev libappindicator1 fonts-liberation redis-server -y
- rvm --default use 2.3.4
- export PATH=/tmp/bundler/ruby/2.3.0/bin:$PATH
- export GEM_PATH=/tmp/bundler/ruby/2.3.0/gems:$GEM_PATH
- export TEST_ENV_NUMBER=0
- psql -c 'create database checkdesk_test0;' -U postgres
- redis-server 2>&1 >/dev/null &
- wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.4.1.deb && sudo dpkg -i --force-confnew elasticsearch-2.4.1.deb && sudo service elasticsearch restart
- sleep 15
- 'echo "script.engine.groovy.inline.update: on" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
- sudo /usr/share/elasticsearch/bin/plugin install analysis-icu
- sudo service elasticsearch restart
- git clone https://github.com/meedan/check-api.git
- d=configurator/check/travis/check-api/; for f in $(find $d -type f); do cp "$f" "check-api/${f/$d/}"; done
- cd check-api
- bundle install --path=/tmp/bundler
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake lapis:api_keys:create_default RAILS_ENV=test
- bundle exec thin -p 13000 -e test -t 60 --threadpool-size=60 --threaded start &
- sleep 5
- cd -
before_script:
- cp config.js.example config.js
- cp aws.json.example aws.json
- mkdir dist
- npm run build
script: npm test
notifications:
  slack:
    secure: gS8DOqLHTUUWpcimRfaxy6/Zexgbp91mdZ3N5556GkJEI90IV53JX+XuJkzMpR5GzmBcai8lb1ZaOGuhWXQl1785KG3pX4gW05GxHhxxuMXgHVQhkw+V48fPv6BJs4wsycDeU+xBeVp6FgeXGyfznDlYxuEdx4CvdvKcjh9QdWZ72iX5ghISzFzrK3RMZtMOSsWPixI2GLOPXR/1BpP7Uz7MzlwqgS7sP1i9AZhNpdsI5YKgiKgl0a1J6Qz3UAE5WF7GKIjde8f0G7blE5N0oiKIO8WPL7JwMlnNHXO0Yf/ghrcEZSO3FscdYdWSeBh7Ja/WGn/H8y9YHfZ7zNbxcOaOcQ2tK/KsOK2PsHa7mhHA/nIWZca0jjkvdNsgjol4P9jfkKBWF1wQSmtk8QYYRQoJTlkYVyMqhGlIeIseesQ4bqibU5O1U96g4kWNvz44d40XvUtTlhy1+4ihnFsNdJVds+MIKftCXUYeS8gUL8gBtMoNYgdBixU5GzfQexaEA4KU58Rv3x4dc1CGmkFIEwQWkxKKaHHthaKh7wFqoLK8EiV9BOAqfH92tqh4JxNrcdTjdX7Z515RYJRZTFmRlWXMHDZEywXxbWcqtGb3OPD/R/Kw4lbhkvRMs+32kE6pa47hgGCRiQnaPRUFrWgwrjIj6K9g1dmLjIAYa77oY4Y=
